-- CreateEnum
CREATE TYPE "VERIFY_STATUS" AS ENUM ('PENDING', 'ACCEPT', 'REFUSE');

-- AlterTable
ALTER TABLE "Apartment" ADD COLUMN     "verified" "VERIFY_STATUS" NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE "RoomRenter" ADD COLUMN     "verified" "VERIFY_STATUS" NOT NULL DEFAULT 'PENDING';
